#!/bin/bash
# By James Waldby - 30 April 2020 - Copyright © 2020 - Offered without
# warranty under GPL v3 terms as at http://www.gnu.org/licenses/gpl.html

# cczoomy provides three functions: 1) Countdown timing (a timer
# updating every 10 seconds); 2) Clock display on a red background; 3)
# function to annotate TI-supplied images.  These functions complement
# operations in yzoomy, which is a script to automatically click on
# pictures in the Zoom Virtual Background setup box.

# Here are five examples of function usage, to a) Countdown specified
# number of seconds, b) Show current time & timezone on red
# background, c-e) Create smaller, annotated versions tG.png, tY.png,
# tR.png of TI-supplied color backgrounds.  Note, in c-e, replace the
# shorthand-indicated color-filenames with actual filenames when you
# run the commands.

# a)      cczoomy countdown 60
# b)      cczoomy timesho
# c)      cczoomy annotate G  green-filename
# d)      cczoomy annotate Y  yellow-filename
# e)      cczoomy annotate R  red-filename

# The countdown and timesho functions overwrite a file in zoom's
# Custom Virtual Background directory.  For this script version, the
# most-recently-changed file in zoom's custom background directory is
# presumed to be the option file.  Before you use this script, either
# go into your .zoom/data/VirtualBkgnd_Custom directory and touch the
# proper file, or in the Settings / Virtual Background window, remove
# and add the option image after any other images, and then if
# necessary recalibrate yzoomy.

# During yzoomy's calibration of the 'option' image, move the mouse
# cursor to the thumbnail for a file that is ok to overwrite within
# .zoom's custom background directory, which as noted above should be
# the last-added file.  Note, the thumbnail appearance in the settings
# window updates only when you restart settings; just overwriting the
# file won't change the thumbnail or the current virtual background.
# The background changes only when a thumbnail other than the current
# thumbnail is clicked, so the countdown function uses a two-click
# sequence after it overwrites a file.

GREENPATH="$HOME/nt/contest/yzoomy-timing/tG.png"
REDPATH="$HOME/nt/contest/yzoomy-timing/tR.png"
CALI=/tmp/yz-timingPixAt
ZVBC="$HOME/.zoom/data/VirtualBkgnd_Custom/"
OUUID="${ZVBC}$(ls -t $ZVBC | head -1)"

# Load calibration data if it exists, else say to do calibration.
[[ -f $CALI ]] && . $CALI
[[ -f $CALI ]] || echo No calibration file found -- You Should Run CalibrateColors
#----------------------------------------------
# Call timesho with no params.  Variable REDPATH = path to red image
function timesho() {
    D=$(date +'%H:%M %Z'); convert $REDPATH -font Bookman-DemiItalic -pointsize 288 -fill white -stroke green -draw "text 100,440 '$D'" time-image.png
    cp time-image.png "$OUUID"
    yzoomy click1 g
    yzoomy click1 o
}
#----------------------------------------------

# The `annotate` function works ok with images from
# <https://www.toastmasters.org/resources/Timer%20Zoom%20Backgrounds>
# which are 3840x2160 in spite of "1920x1080" appearing within the
# file names.  Use this function 3 times (as shown in earlier function
# usage examples) to create green, yellow, and red images suitably
# sized and annotated for use with countdown and timesho.  Example:
# `cczoomy annotate G
# en-toastmasters-TA662D-toastmasters-zoom-virtual-wordmark-bk-timer-green-1920x1080-c1.jpg`
# will copy that image to file tG.png.  The input .jpg image is
# 3840x2160 pixels (for April 2020 TI files).  The .png output will be
# half size -- suitable for use with countdown or timesho -- and will
# have large-letter annotations left and right.
function annotate() {
    convert $2  -resize 50% -font Bookman-Light -pointsize 488 -fill black -stroke white -draw "text 140,840 $1" -draw "text 1450,840 $1" t${1}.png
    ls -l t${1}.png
}
#----------------------------------------------
# Call countdown with 1 param: seconds to count down from.  During
# most of the countdown, an image is created and displayed every 10
# seconds, with the number of seconds remaining in countdown.  During
# the last few seconds, the image updates each second.  After the
# interval, this uses timesho to show a time-stamped red image.  After
# 6 seconds with that, goes to plain red image.

# Shell variable OUUID = path into your ~/.zoom directory for the
# image that was calibrated as the 'option' picture.  Variable
# GREENPATH should be a path to the image you use as a green
# background, which `convert` will create a timing-modified copy of,
# in file time-image.png. Note, `convert` is an ImageMagick program.
function countdown() {
    left=$1
    PRET=no
    TIME=$(date +'%S')
    ONES=${TIME: -1:1}
    while [[ $left -gt 0 ]]; do
        TIME=$(date +'%S')
        if [[ $TIME != $PRET ]]; then
            sho=n
            [[ ${TIME: -1:1} = $ONES ]] && sho=y
            [[ $left -lt 6 ]]  && sho=y
            if [[ $sho = y ]]; then
                convert $GREENPATH -font Bookman-DemiItalic -pointsize 222 -fill blue -draw "text 440,440 '$left'" time-image.png
                cp time-image.png "$OUUID"
                yzoomy click1 g
                yzoomy click1 o
            fi
            PRET=$TIME
            left=$((left-1))
        fi
        sleep 0.2
    done
    timesho
    sleep 6
    yzoomy click1 r
}
#----------------------------------------------------
fToRun=$1;  shift     # First param = function to run
$fToRun $*            # Run it with other params
